#!/usr/bin/env bash
#
# Extract reference assets from the upstream WPSD appliance image.
#
# Dev-time only: the container build never reads the .img. This populates
#   rootfs/etc/...        configs that ship in our image
#   reference/units/      the systemd units the systemctl shim is written against
#   reference/rootfs/     read-only copies kept for diffing (gitignored)
#
# The image is an MBR disk with a vfat /boot at sector 8192 and an ext4 root at
# sector 1056768. macOS cannot mount ext4, so the work happens inside a
# privileged Linux container; mount-by-offset avoids relying on partition device
# nodes, which Docker Desktop's /dev does not create for loop partitions.
#
set -euo pipefail

# `--units-from-upstream` fetches only reference/units/, from W0CHP's unit-file
# repo, and needs no appliance image. Useful for reading the shim's specification
# without a 3.8 GB download; note 12 of the 71 units differ slightly from what the
# Trixie image actually ships, so the image wins when you have it.
if [[ ${1:-} == --units-from-upstream ]]; then
    REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
    cd "$REPO"
    echo "==> fetching systemd units from WPSD_unit_files"
    rm -rf reference/units
    mkdir -p reference/units/upstream
    git clone -q --depth 1 https://repo.w0chp.net/WPSD-Dev/WPSD_unit_files.git /tmp/wpsd-units
    cp -a /tmp/wpsd-units/*.service /tmp/wpsd-units/*.timer reference/units/upstream/
    rm -rf /tmp/wpsd-units
    echo "    $(find reference/units -type f | wc -l | tr -d ' ') unit files in reference/units/upstream/"
    exit 0
fi

IMG="${1:-WPSD_RPi-Trixie.img}"
ROOT_OFFSET=$((1056768 * 512))
ROOT_SIZE=$((7056249 * 512))
BOOT_OFFSET=$((8192 * 512))
BOOT_SIZE=$((1048576 * 512))

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

[[ -f "$IMG" ]] || { echo "error: $IMG not found in $REPO" >&2; exit 1; }

echo "==> extracting reference assets from $IMG"

docker run --rm --privileged \
  -v "$REPO:/work" \
  -e "ROOT_OFFSET=$ROOT_OFFSET" -e "ROOT_SIZE=$ROOT_SIZE" \
  -e "BOOT_OFFSET=$BOOT_OFFSET" -e "BOOT_SIZE=$BOOT_SIZE" \
  -e "IMG=$IMG" \
  debian:trixie-slim bash -euo pipefail -c '
mkdir -p /mnt/img
mount -t ext4 -o "ro,loop,offset=${ROOT_OFFSET},sizelimit=${ROOT_SIZE}" "/work/${IMG}" /mnt/img

R=/mnt/img
OUT=/work/rootfs
REF=/work/reference

# --- systemd units: the specification for the shim, not shipped in the image ---
# These are W0CHP's files verbatim and are NOT committed to this repository --
# they are generated here, and gitignored. 58 of the 71 are byte-identical to
# repo.w0chp.net/WPSD-Dev/WPSD_unit_files, so `--units-from-upstream` can fetch
# them instead if you do not have the appliance image.
mkdir -p "$REF/units/etc" "$REF/units/lib"
find "$R/etc/systemd/system"  -maxdepth 1 -type f -exec cp -a {} "$REF/units/etc/"  \;
find "$R/lib/systemd/system"  -maxdepth 1 -type f \
     \( -name "mmdvm*"   -o -name "*gateway*" -o -name "*parrot*" \
     -o -name "pistar-*" -o -name "ysf2*"     -o -name "dmr2*"    \
     -o -name "nxdn2*"   -o -name "timeserver*" -o -name "timercontrol*" \
     -o -name "nextion*" \) -exec cp -a {} "$REF/units/lib/" \;

# --- nginx: vhosts and the shared default.d snippets ---
cp -a "$R/etc/nginx/sites-available/wpsd"           "$OUT/etc/nginx/sites-available/"
cp -a "$R/etc/nginx/sites-available/captive-portal"  "$OUT/etc/nginx/sites-available/"
cp -a "$R"/etc/nginx/default.d/*.conf                "$OUT/etc/nginx/default.d/"

# --- WPSD config seeds: copied to /etc on first run, never overwritten after ---
D="$OUT/etc/wpsd-defaults/etc"
for f in mmdvmhost dmrgateway ysfgateway ysf2dmr ysf2p25 ysf2nxdn dmr2ysf dmr2nxdn \
         nxdn2dmr p25gateway nxdngateway aprsgateway dapnetgateway ircddbgateway \
         WPSD-Dashboard-Config.ini wpsd-css.ini wpsd-upnp-rules ircddblocal.php \
         .WPSD_config dapnetapi.key pistar-remote ; do
    [[ -e "$R/etc/$f" ]] && cp -a "$R/etc/$f" "$D/" || echo "    (skip /etc/$f)"
done
[[ -d "$R/etc/WPSD_config_mgr" ]] && cp -a "$R/etc/WPSD_config_mgr" "$D/"
# NB: not /var/www/.htpasswd -- the Dockerfile generates a fresh bcrypt hash for
# pi-star/raspberry instead of copying upstream's, and /etc/WPSD-release is empty
# and created by 01-init.

# --- /usr/local/etc: ship only what is NOT regenerated by wpsd-hostfile-update ---
U="$OUT/etc/wpsd-defaults/usr-local-etc"
for f in RSSI.dat CCS_Hosts.txt NXDNHostsLocal.txt P25HostsLocal.txt ; do
    [[ -e "$R/usr/local/etc/$f" ]] && cp -a "$R/usr/local/etc/$f" "$U/"
done
cp -a "$R"/usr/local/etc/TIME_*.ambe "$R"/usr/local/etc/TIME_*.indx "$U/" 2>/dev/null || true
for d in DMR_Audio NXDN_Audio P25_Audio ; do
    [[ -d "$R/usr/local/etc/$d" ]] && cp -a "$R/usr/local/etc/$d" "$U/"
done

# --- read-only reference copies, for diffing during development ---
mkdir -p "$REF/rootfs"
cp -a "$R/etc/fstab"        "$REF/rootfs/fstab"
cp -a "$R/etc/rc.local"     "$REF/rootfs/rc.local"
cp -a "$R/etc/issue"        "$REF/rootfs/issue"
cp -a "$R/etc/passwd"       "$REF/rootfs/passwd"
cp -a "$R/etc/group"        "$REF/rootfs/group"
cp -a "$R/usr/local/sbin"   "$REF/rootfs/usr-local-sbin"
cp -a "$R/etc/php/8.4/fpm/pool.d/www.conf" "$REF/rootfs/php-fpm-www.conf"
# the two non-apt shared libs the shipped armhf binaries need (reference image only)
mkdir -p "$REF/rootfs/lib-armhf"
cp -a "$R/usr/lib/libwiringPi.so.2.52" "$R/usr/lib/libwiringPiDev.so.2.52" \
      "$R/usr/local/lib/libArduiPi_OLED.so.1.0" "$REF/rootfs/lib-armhf/"

# --- the authoritative list of systemctl calls the shim must satisfy ---
grep -rhoE "systemctl (--[a-z]+ )?[a-z-]+ [a-zA-Z0-9@._-]*" \
     "$R/var/www/dashboard" "$R/usr/local/sbin" 2>/dev/null \
  | sed "s/  */ /g; s/ *$//" | sort -u > /work/tests/systemctl-calls.txt

umount /mnt/img
echo "    done"
'

echo "==> summary"
printf "    units:            %s\n" "$(find reference/units -type f | wc -l | tr -d ' ')"
printf "    config seeds:     %s\n" "$(find rootfs/etc/wpsd-defaults -type f | wc -l | tr -d ' ')"
printf "    systemctl calls:  %s\n" "$(wc -l < tests/systemctl-calls.txt | tr -d ' ')"
